version: '3.8'

networks:
    angularBase:
      driver: bridge

services:
    mysql-db:
        image: mysql:latest
        container_name: angbase_db # Replace angbase with your project prefix
        restart: always
        environment:
            MYSQL_DATABASE: 'angulatBase'
            MYSQL_USER: 'sporos'
            MYSQL_PASSWORD: '222'
            MYSQL_ROOT_PASSWORD: '5404271'
        ports:
            - '4001:3306'
        expose:
            - '4001'
        volumes: 
            - /home/jab/.mysql_data/angularBase_db:/var/lib/mysql
        networks:
            - angularBase

    web-app:     
        build: 
            context: ./webapp
            dockerfile: Dockerfile_development
        container_name: angbase_web # Replace angbase with your project prefix
        ports:
            - '4201:4200'
        expose:
            - '4201'
        volumes:
            - ./webapp/src:/app/src # Keep in mind node_modules must be in the Dev dir for this to work...
        depends_on:
            - mysql-db            
        networks:
            - angularBase
        # command: tail -f /dev/null #This will keep the image active

    http-service:   #This service will start and will connect to db after 5sec
        build: 
            context: ./http-service
            dockerfile: Dockerfile
        container_name: angbase_rest # Replace angbase with your project prefix
        ports:
            - '5001:5001'
        expose:
            - '5001'
        volumes:
            - ./http-service:/app
            - ./http-services/var/logs:/app/.var/logs
        depends_on:
            - mysql-db
            - web-app
        networks:
            - angularBase
        # command: tail -f /dev/null #This will keep the image active

