version: '3.8'

networks:
    localdev:
      driver: bridge

services:
    mysql-db:
        image: mysql:latest
        container_name: angbase_db # Replace angbase with your project prefix
        restart: always
        environment:
            MYSQL_DATABASE: 'angulatBase'
            MYSQL_USER: 'sporos'
            MYSQL_PASSWORD: '222'
            MYSQL_ROOT_PASSWORD: '5404271'
        ports:
            - '3307:3306'
        expose:
            - '3307'
        volumes: 
            - /home/jab/.mysql_data/angularBase_db:/var/lib/mysql
        networks:
            - localdev

    http-service:   #This service will start and will connect to db after 5sec
        build: 
            context: ./http-service
            dockerfile: Dockerfile
        container_name: angbase_rest # Replace angbase with your project prefix
        ports:
            - '5000:5000'
        expose:
            - '5000'
        volumes:
            - ./http-service:/app
            - /home/jab/.var/logs:/app/.var/logs
        depends_on:
            - mysql-db
        networks:
            - localdev
        # command: tail -f /dev/null #This will keep the image active
        
    web-app:     
        build: 
            context: ./webapp
            dockerfile: Dockerfile_development
        container_name: angbase_web # Replace angbase with your project prefix
        ports:
            - '4200:4200'
        expose:
            - '4200'
        volumes:
            - ./webapp/src:/app/src # Keep in mind node_modules must be in the Dev dir for this to work...
        depends_on:
            - mysql-db
            - http-service
        networks:
            - localdev
        # command: tail -f /dev/null #This will keep the image active

