#ProjectDetails
projectName : angulatBase

#Logging System Details
filename : angulatBase.log
level : debug

#Database system details
dbuserName : root
dbpassword : '5404271'
dbhost : 'angbase_db' 
dbport : 3306
dbname : angularBase

#CherryPi Settings
chpHost : 0.0.0.0
chpPort : 5000
