#ProjectDetails
projectName : angulatBase

#Logging System Details
filename : angulatBase.log
level : debug

#Database system details
dbuserName : jab
dbpassword : 222
dbhost : 127.0.0.1
dbname : hydroclear

#CherryPi Settings
chpHost : 0.0.0.0
chpPort : 5000
